Repository based-4806/BasedSurvey, pull requests merged in 2023-03, with the labels that each got.

#16 made it possible to test
  src/main/java/com/based/basedsurvey/data/MultiplechoiceQuestion.java
  src/main/java/com/based/basedsurvey/data/Survey.java
Labels: bug

#17 removed useless close functions
  src/test/java/com/based/basedsurvey/data/MultiplechoiceQuestionTest.java
  src/test/java/com/based/basedsurvey/data/OpenAnswerQuestionTest.java
  src/test/java/com/based/basedsurvey/data/RangeQuestionTest.java
  src/test/java/com/based/basedsurvey/data/SurveyTest.java
Labels: bug

#15 added mcq
  src/main/java/com/based/basedsurvey/BasedSurveyApplication.java
  src/main/java/com/based/basedsurvey/controller/WebQuestionController.java
  src/main/resources/templates/EditQuestion.html
  src/test/java/com/based/basedsurvey/controller/WebQuestionControllerTest.java
Labels: enhancement

#18 fixed other orm classes for testing
  src/main/java/com/based/basedsurvey/data/OpenAnswerQuestion.java
  src/main/java/com/based/basedsurvey/data/RangeQuestion.java
Labels: bug

#19 added edit for range question
  src/main/java/com/based/basedsurvey/controller/WebQuestionController.java
  src/main/java/com/based/basedsurvey/data/QuestionTypes.java
  src/main/resources/templates/EditQuestion.html
  src/test/java/com/based/basedsurvey/controller/WebQuestionControllerTest.java
Labels: enhancement

#20 added uml for data
  documentation/Milestone1DataUml.png
Labels: documentation

#21 Range Question edit
  src/main/java/com/based/basedsurvey/controller/WebQuestionController.java
  src/main/resources/templates/EditQuestion.html
  src/test/java/com/based/basedsurvey/controller/WebQuestionControllerTest.java
Labels: enhancement

#24 fixed edit link in index page
  src/main/resources/templates/index.html
Labels: bug

#26 Added Edit Survey Functionality
  src/main/java/com/based/basedsurvey/controller/WebEditSurveyController.java
  src/main/java/com/based/basedsurvey/data/QuestionTypes.java
  src/main/java/com/based/basedsurvey/data/Survey.java
  src/main/resources/templates/newSurvey.html
Labels: based

#22 Added ability to fill out surveys
  src/main/java/com/based/basedsurvey/controller/FillSurveyController.java
  src/main/resources/templates/Answer.html
  src/main/resources/templates/SurveyFillIssue.html
  src/main/resources/templates/index.html
Labels: enhancement, based

#36 Added db schema
  documentation/db_schema.PNG
Labels: documentation

#75 Added method to open and close survey, fixed tests
  src/main/java/com/based/basedsurvey/controller/WebEditSurveyController.java
  src/main/java/com/based/basedsurvey/data/Survey.java
  src/main/resources/templates/newSurvey.html
  src/test/java/com/based/basedsurvey/controller/FillSurveyControllerTest.java
  src/test/java/com/based/basedsurvey/controller/WebQuestionControllerTest.java
  src/test/java/com/based/basedsurvey/data/SurveyTest.java
Labels: enhancement

#76 added test for WebEditSurveyController.
  src/test/java/com/based/basedsurvey/controller/WebEditSurveyControllerTest.java
  src/test/java/com/based/basedsurvey/controller/WebQuestionControllerTest.java
Labels: enhancement

#80 added additional info field to questions
  src/main/java/com/based/basedsurvey/controller/FillSurveyController.java
  src/main/java/com/based/basedsurvey/controller/ResultsSurveyController.java
  src/main/java/com/based/basedsurvey/controller/WebEditSurveyController.java
  src/main/java/com/based/basedsurvey/controller/WebQuestionController.java
  src/main/java/com/based/basedsurvey/data/Question.java
  src/main/resources/templates/EditQuestion.html
  src/main/resources/templates/newSurvey.html
  src/test/java/com/based/basedsurvey/controller/FillSurveyControllerTest.java
  src/test/java/com/based/basedsurvey/controller/ResultsSurveyControllerTest.java
  src/test/java/com/based/basedsurvey/controller/WebEditSurveyControllerTest.java
  src/test/java/com/based/basedsurvey/controller/WebQuestionControllerTest.java
  src/test/java/com/based/basedsurvey/data/MultiplechoiceQuestionTest.java
  src/test/java/com/based/basedsurvey/data/OpenAnswerQuestionTest.java
  src/test/java/com/based/basedsurvey/data/RangeQuestionTest.java
  src/test/java/com/based/basedsurvey/data/SurveyTest.java
Labels: enhancement

#81 Added feature so that questions cannot be edited if survey is open
  src/main/resources/templates/EditQuestion.html
  src/test/java/com/based/basedsurvey/controller/WebEditSurveyControllerTest.java
Labels: enhancement

#93 updated data UML to include additional info field
  documentation/Milestone2DataUML.JPG
Labels: documentation

#91 updated db schema to include additional info field and many-one arrows
  documentation/Milestone1dbschema.png
  documentation/Milestone2dbschema.JPG
Labels: documentation

#104 added wojak chad as favicon
  src/main/resources/static/favicon.ico
Labels: enhancement, based
